#!/bin/bash

# Remove new-vim files
sudo rm -r ~/.vim/*

# Restore old vim
cp -r ~/.my-vim/old-vim/* ~/.vim

# Restore old vimrc file
cp ~/.my-vim/old-vim/.vimrc ~/.vimrc

# Remove dependencies
~/.my-vim/dependencies remove

# Remove folder
sudo rm -r ~/.my-vim
